### ISSUE TITLE
CollectionChanged event not available

### ISSUE THREAD

**Issue by ohjohnsen** [ENikS/ObservableCollectionEx#2]
The CollectionChanged event is not available on a ObservableCollectionEx collection.  Is there another way to subscribe to changes?

**Comment by ENikS** [comment]
I am not sure what is the issue?

This is the sample how to use these https://www.codeproject.com/Articles/249311/Enhanced-ObservableCollection

**Comment by ohjohnsen** [comment]
CollectionChanged event is available on an ObservableCollection object, and on an ObservableCollectionEx object it isn't.  See image:
![screenshot](https://user-images.githubusercontent.com/16133835/30665644-ef822ada-9e51-11e7-9dea-d03c87d8f3ab.png)

I want to use it in this manner: https://stackoverflow.com/questions/8986105/how-to-detect-if-an-item-in-my-observablecollection-has-changed :)

**Comment by ENikS** [comment]
You have to cast it into ``INotifyPropertyChanged``:
```C#
((INotifyPropertyChanged)collectionInstance).CollectionChanged += handler;
```

**Comment by ohjohnsen** [comment]
Casting it into `INotifyCollectionChanged` worked like a charm.  Thank you!

    ((INotifyCollectionChanged)ScreenList).CollectionChanged += ScreenList_CollectionChanged;
