### ISSUE TITLE
Readonly variants

### ISSUE THREAD

**Issue by SjoerdNijboer** [ENikS/ObservableCollectionEx#3]
I would love to have a ReadonlyObservablecollectionEx<T> so I can expose things more safely.

**Comment by ENikS** [comment]
Care to sent a pull request?

**Comment by SjoerdNijboer** [comment]
I will do so before next week.

**Comment by Anton-V-K** [comment]
Has this feature been implemented somehow?

**Comment by ENikS** [comment]
No, it was never implemented
